name: Publish Python on TestPyPi
on:
  push:
    tags:
      - "v*-dev[0-9]"

jobs:
  build-n-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v3
        with:
          ref: dev

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install pep517
        run: >-
          python -m pip install pep517 --user

      - name: Build a binary wheel and a source tarball
        run: >-
          python -m pep517.build --source --binary --out-dir dist/ ./

      - name: Publish distribution to Test PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.pypi_test_password }}
          repository_url: https://test.pypi.org/legacy/
